---
name: ci

on: [push]

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          docker login -u harshdesai7979 -p password1
          docker build -f python/Dockerfile . -t harshdesai7979/stellarhealthpython:latest --platform linux/amd64
      
