---
name: ci

env:

on: [push]

jobs:
  docker:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dockerize
        uses: manusa/actions-publish-docker@v1.1.2
        with:
          name: harshdesai7979/stellarhealthpython
          username: harshdesai7979
          password: password1
          tag: latest
