---
name: ci

on: [push]

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Python Test
        run: |
          cd python/
          pytest test.py
      - name: Go Test
        run: |
          cd go/
          go test
      - name: Build and push python container
        run: |
          docker login -u harshdesai7979 -p password1
          cd python/
          docker build -f Dockerfile . -t harshdesai7979/stellarhealthpython:latest --platform linux/amd64
          docker push harshdesai7979/stellarhealthpython:latest
